//
//  Spell.h
//  momom
//
//  Created by Sven de Ridder on 9/24/13.
//  Copyright (c) 2013 svenr. All rights reserved.
//

#ifndef momom_Spell_h
#define momom_Spell_h

namespace momom {
    
    enum class Spell {
        
        // Nature
        EarthToMud = 0,
        ResistElements = 1,
        WallOfStone = 2,
        GiantStrength = 3,
        Web = 4,
        WarBears = 5,
        StoneSkin = 6,
        WaterWalking = 7,
        Sprites = 8,
        EarthLore = 9,
        CracksCall = 10,
        NaturesEye = 11,
        IceBolt = 12,
        GiantSpiders = 13,
        ChangeTerrain = 14,
        PathFinding = 15,
        Cockatrices = 16,
        Transmute = 17,
        NaturesCures = 18,
        Basilisk = 19,
        ElementalArmor = 20,
        Petrify = 21,
        StoneGiant = 22,
        IronSkin = 23,
        IceStorm = 24,
        EarthQuake = 25,
        Gorgons = 26,
        MoveFortress = 27,
        GaiasBlessing = 28,
        EarthElemental = 29,
        Regeneration = 30,
        Behemoth = 31,
        Entangle = 32,
        NaturesAwareness = 33,
        CallLightning = 34,
        Colossus = 35,
        EarthGate = 36,
        HerbMastery = 37,
        GreatWyrm = 38,
        NaturesWrath = 39,
        
        // Sorcery
        ResistMagic = 40,
        DispelMagicTrue = 41,
        FloatingIsland = 42,
        GuardianWind = 43,
        PhantomWarriors = 44,
        Confusion = 45,
        WordOfRecall = 46,
        CounterMagic = 47,
        Nagas = 48,
        PsionicBlast = 49,
        Blur = 50,
        DisenchantTrue = 51,
        Vertigo = 52,
        SpellLock = 53,
        EnchantRoad = 54,
        Flight = 55,
        WindMastery = 56,
        SpellBlast = 57,
        AuraOfMajesty = 58,
        PhantomBeast = 59,
        DisjunctionTrue = 60,
        Invisibility = 61,
        WindWalking = 62,
        Banish = 63,
        StormGiant = 64,
        AirElemental = 65,
        MindStorm = 66,
        Statis = 67,
        MagicImmunity = 68,
        Haste = 69,
        Djinn = 70,
        SpellWard = 71,
        CreatureBinding = 72,
        MassInvisibility = 73,
        GreatUnsummoning = 74,
        SpellBinding = 75,
        FlyingFortress = 76,
        SkyDrake = 77,
        SuppressMagic = 78,
        TimeStop = 79,
        
        // Chaos
        WarpWood = 80,
        Disrupt = 81,
        FireBolt = 82,
        HellHounds = 83,
        Corruption = 84,
        EldritchWeapon = 85,
        WallOfFire = 86,
        Shatter = 87,
        WarpCreature = 88,
        FireElemental = 89,
        LightningBolt = 90,
        FireGiant = 91,
        ChaosChannels = 92,
        FlameBlade = 93,
        Gargoyles = 94,
        Fireball = 95,
        Doombat = 96,
        RaiseVolcano = 97,
        Immolation = 98,
        Chimeras = 99,
        WarpLightning = 100,
        MetalFires = 101,
        ChaosSpawn = 102,
        DoomBolt = 103,
        MagicVortex = 104,
        Efreet = 105,
        FireStorm = 106,
        WarpReality = 107,
        FlameStrike = 108,
        ChaosRift = 109,
        Hydra = 110,
        Disintegrate = 111,
        MeteorStorm = 112,
        GreatWasting = 113,
        CallChaos = 114,
        ChaosSurge = 115,
        DoomMastery = 116,
        GreatDrake = 117,
        CallTheVoid = 118,
        Armageddon = 119,
        
        // Life
        Bless = 120,
        StarFires = 121,
        Endurance = 122,
        HolyWeapon = 123,
        Healing = 124,
        HolyArmor = 125,
        JustCause = 126,
        TrueLight = 127,
        GuardianSpirit = 128,
        Heroism = 129,
        TrueSight = 130,
        PlaneShift = 131,
        Resurrection = 132,
        DispelEvil = 133,
        PlanarSeal = 134,
        Unicorns = 135,
        RaiseDead = 136,
        PlanarTravel = 137,
        HeavenlyLight = 138,
        Prayer = 139,
        Lionheart = 140,
        Incarnation = 141,
        Invulnerability = 142,
        Righteousness = 143,
        Prosperity = 144,
        AltarOfBattle = 145,
        Angel = 146,
        StreamOfLife = 147,
        MassHealing = 148,
        HolyWord = 149,
        HighPrayer = 150,
        Inspirations = 151,
        AstralGate = 152,
        HolyArms = 153,
        Consecration = 154,
        LifeForce = 155,
        Tranquility = 156,
        Crusade = 157,
        ArchAngel = 158,
        CharmOfLife = 159,
        
        // Death
        Skeletons = 160,
        Weakness = 161,
        DarkRituals = 162,
        CloakOfFear = 163,
        BlackSleep = 164,
        Ghouls = 165,
        LifeDrain = 166,
        Terror = 167,
        Darkness = 168,
        ManaLeak = 169,
        DrainPower = 170,
        Possession = 171,
        Lycanthropy = 172,
        BlackPrayer = 173,
        BlackChannels = 174,
        NightStalker = 175,
        Subversion = 176,
        WallOfDarkness = 177,
        Berserk = 178,
        ShadowDemons = 179,
        WraithForm = 180,
        Wrack = 181,
        EvilPresence = 182,
        Wraiths = 183,
        CloudOfShadow = 184,
        WarpNode = 185,
        BlackWind = 186,
        ZombieMastery = 187,
        Famine = 188,
        CursedLands = 189,
        CruelUnminding = 190,
        WordOfDeath = 191,
        DeathKnights = 192,
        DeathSpell = 193,
        AnimateDead = 194,
        Pestilence = 195,
        EternalNight = 196,
        EvilOmens = 197,
        DeathWish = 198,
        DemonLord = 199,
        
        // Arcane
        MagicSpirit = 200,
        DispelMagic = 201,
        SummoningCircle = 202,
        DisenchantArea = 203,
        RecallHero = 204,
        DetectMagic = 205,
        EnchantItem = 206,
        SummonHero = 207,
        Awareness = 208,
        Disjunction = 209,
        CreateArtifact = 210,
        SummonChampion = 211,
        SpellOfMastery = 212,
        SpellOfReturn = 213
    };
}

#endif
