//
//  Spell.cpp
//  momom
//
//  Created by Sven de Ridder on 10/1/13.
//  Copyright (c) 2013 svenr. All rights reserved.
//

#include "Spell.h"

namespace momom {
    
    const char* toString(Spell s) {
        switch(s) {
        case Spell::EarthToMud: return "Earth to Mud";
        case Spell::ResistElements: return "Resist Elements";
        case Spell::WallOfStone: return "Wall of Stone";
        case Spell::GiantStrength: return "Giant Strength";
        case Spell::Web: return "Web";
        case Spell::WarBears: return "War Bears";
        case Spell::StoneSkin: return "Stone Skin";
        case Spell::WaterWalking: return "Water Walking";
        case Spell::Sprites: return "Sprites";
        case Spell::EarthLore: return "Earth Lore";
        case Spell::CracksCall: return "Cracks Call";
        case Spell::NaturesEye: return "Nature's Eye";
        case Spell::IceBolt: return "Ice Bolt";
        case Spell::GiantSpiders: return "Giant Spiders";
        case Spell::ChangeTerrain: return "Change Terrain";
        case Spell::PathFinding: return "Path Finding";
        case Spell::Cockatrices: return "Cockatrices";
        case Spell::Transmute: return "Transmute";
        case Spell::NaturesCures: return "Nature's Cures";
        case Spell::Basilisk: return "Basilisk";
        case Spell::ElementalArmor: return "Elemental Armor";
        case Spell::Petrify: return "Petrify";
        case Spell::StoneGiant: return "Stone Giant";
        case Spell::IronSkin: return "Iron Skin";
        case Spell::IceStorm: return "Ice Storm";
        case Spell::EarthQuake: return "Earth Quake";
        case Spell::Gorgons: return "Gorgons";
        case Spell::MoveFortress: return "Move Fortress";
        case Spell::GaiasBlessing: return "Gaia's Blessing";
        case Spell::EarthElemental: return "Earth Elemental";
        case Spell::Regeneration: return "Regeneration";
        case Spell::Behemoth: return "Behemoth";
        case Spell::Entangle: return "Entangle";
        case Spell::NaturesAwareness: return "Nature's Awareness";
        case Spell::CallLightning: return "Call Lightning";
        case Spell::Colossus: return "Colossus";
        case Spell::EarthGate: return "Earth Gate";
        case Spell::HerbMastery: return "Herb Mastery";
        case Spell::GreatWyrm: return "Great Wyrm";
        case Spell::NaturesWrath: return "Nature's Wrath";
        case Spell::ResistMagic: return "Resist Magic";
        case Spell::DispelMagicTrue: return "Dispel Magic True";
        case Spell::FloatingIsland: return "Floating Island";
        case Spell::GuardianWind: return "Guardian Wind";
        case Spell::PhantomWarriors: return "Phantom Warriors";
        case Spell::Confusion: return "Confusion";
        case Spell::WordOfRecall: return "Word of Recall";
        case Spell::CounterMagic: return "Counter Magic";
        case Spell::Nagas: return "Nagas";
        case Spell::PsionicBlast: return "Psionic Blast";
        case Spell::Blur: return "Blur";
        case Spell::DisenchantTrue: return "Disenchant True";
        case Spell::Vertigo: return "Vertigo";
        case Spell::SpellLock: return "Spell Lock";
        case Spell::EnchantRoad: return "Enchant Road";
        case Spell::Flight: return "Flight";
        case Spell::WindMastery: return "Wind Mastery";
        case Spell::SpellBlast: return "Spell Blast";
        case Spell::AuraOfMajesty: return "Aura of Majesty";
        case Spell::PhantomBeast: return "Phantom Beast";
        case Spell::DisjunctionTrue: return "Disjunction True";
        case Spell::Invisibility: return "Invisibility";
        case Spell::WindWalking: return "Wind Walking";
        case Spell::Banish: return "Banish";
        case Spell::StormGiant: return "Storm Giant";
        case Spell::AirElemental: return "Air Elemental";
        case Spell::MindStorm: return "Mind Storm";
        case Spell::Statis: return "Statis";
        case Spell::MagicImmunity: return "Magic Immunity";
        case Spell::Haste: return "Haste";
        case Spell::Djinn: return "Djinn";
        case Spell::SpellWard: return "Spell Ward";
        case Spell::CreatureBinding: return "Creature Binding";
        case Spell::MassInvisibility: return "Mass Invisibility";
        case Spell::GreatUnsummoning: return "Great Unsummoning";
        case Spell::SpellBinding: return "Spell Binding";
        case Spell::FlyingFortress: return "Flying Fortress";
        case Spell::SkyDrake: return "Sky Drake";
        case Spell::SuppressMagic: return "Suppress Magic";
        case Spell::TimeStop: return "Time Stop";
        case Spell::WarpWood: return "Warp Wood";
        case Spell::Disrupt: return "Disrupt";
        case Spell::FireBolt: return "Fire Bolt";
        case Spell::HellHounds: return "Hell Hounds";
        case Spell::Corruption: return "Corruption";
        case Spell::EldritchWeapon: return "Eldritch Weapon";
        case Spell::WallOfFire: return "Wall of Fire";
        case Spell::Shatter: return "Shatter";
        case Spell::WarpCreature: return "Warp Creature";
        case Spell::FireElemental: return "Fire Elemental";
        case Spell::LightningBolt: return "Lightning Bolt";
        case Spell::FireGiant: return "Fire Giant";
        case Spell::ChaosChannels: return "Chaos Channels";
        case Spell::FlameBlade: return "Flame Blade";
        case Spell::Gargoyles: return "Gargoyles";
        case Spell::Fireball: return "Fireball";
        case Spell::Doombat: return "Doombat";
        case Spell::RaiseVolcano: return "Raise Volcano";
        case Spell::Immolation: return "Immolation";
        case Spell::Chimeras: return "Chimeras";
        case Spell::WarpLightning: return "Warp Lightning";
        case Spell::MetalFires: return "Metal Fires";
        case Spell::ChaosSpawn: return "Chaos Spawn";
        case Spell::DoomBolt: return "Doom Bolt";
        case Spell::MagicVortex: return "Magic Vortex";
        case Spell::Efreet: return "Efreet";
        case Spell::FireStorm: return "Fire Storm";
        case Spell::WarpReality: return "Warp Reality";
        case Spell::FlameStrike: return "Flame Strike";
        case Spell::ChaosRift: return "Chaos Rift";
        case Spell::Hydra: return "Hydra";
        case Spell::Disintegrate: return "Disintegrate";
        case Spell::MeteorStorm: return "Meteor Storm";
        case Spell::GreatWasting: return "Great Wasting";
        case Spell::CallChaos: return "Call Chaos";
        case Spell::ChaosSurge: return "Chaos Surge";
        case Spell::DoomMastery: return "Doom Mastery";
        case Spell::GreatDrake: return "Great Drake";
        case Spell::CallTheVoid: return "Call the Void";
        case Spell::Armageddon: return "Armageddon";
        case Spell::Bless: return "Bless";
        case Spell::StarFires: return "Star Fires";
        case Spell::Endurance: return "Endurance";
        case Spell::HolyWeapon: return "Holy Weapon";
        case Spell::Healing: return "Healing";
        case Spell::HolyArmor: return "Holy Armor";
        case Spell::JustCause: return "Just Cause";
        case Spell::TrueLight: return "True Light";
        case Spell::GuardianSpirit: return "Guardian Spirit";
        case Spell::Heroism: return "Heroism";
        case Spell::TrueSight: return "True Sight";
        case Spell::PlaneShift: return "Plane Shift";
        case Spell::Resurrection: return "Resurrection";
        case Spell::DispelEvil: return "Dispel Evil";
        case Spell::PlanarSeal: return "Planar Seal";
        case Spell::Unicorns: return "Unicorns";
        case Spell::RaiseDead: return "Raise Dead";
        case Spell::PlanarTravel: return "Planar Travel";
        case Spell::HeavenlyLight: return "Heavenly Light";
        case Spell::Prayer: return "Prayer";
        case Spell::Lionheart: return "Lionheart";
        case Spell::Incarnation: return "Incarnation";
        case Spell::Invulnerability: return "Invulnerability";
        case Spell::Righteousness: return "Righteousness";
        case Spell::Prosperity: return "Prosperity";
        case Spell::AltarOfBattle: return "Altar of Battle";
        case Spell::Angel: return "Angel";
        case Spell::StreamOfLife: return "Stream of Life";
        case Spell::MassHealing: return "Mass Healing";
        case Spell::HolyWord: return "Holy Word";
        case Spell::HighPrayer: return "High Prayer";
        case Spell::Inspirations: return "Inspirations";
        case Spell::AstralGate: return "Astral Gate";
        case Spell::HolyArms: return "Holy Arms";
        case Spell::Consecration: return "Consecration";
        case Spell::LifeForce: return "Life Force";
        case Spell::Tranquility: return "Tranquility";
        case Spell::Crusade: return "Crusade";
        case Spell::ArchAngel: return "Arch Angel";
        case Spell::CharmOfLife: return "Charm of Life";
        case Spell::Skeletons: return "Skeletons";
        case Spell::Weakness: return "Weakness";
        case Spell::DarkRituals: return "Dark Rituals";
        case Spell::CloakOfFear: return "Cloak of Fear";
        case Spell::BlackSleep: return "Black Sleep";
        case Spell::Ghouls: return "Ghouls";
        case Spell::LifeDrain: return "Life Drain";
        case Spell::Terror: return "Terror";
        case Spell::Darkness: return "Darkness";
        case Spell::ManaLeak: return "Mana Leak";
        case Spell::DrainPower: return "Drain Power";
        case Spell::Possession: return "Possession";
        case Spell::Lycanthropy: return "Lycanthropy";
        case Spell::BlackPrayer: return "Black Prayer";
        case Spell::BlackChannels: return "Black Channels";
        case Spell::NightStalker: return "Night Stalker";
        case Spell::Subversion: return "Subversion";
        case Spell::WallOfDarkness: return "Wall of Darkness";
        case Spell::Berserk: return "Berserk";
        case Spell::ShadowDemons: return "Shadow Demons";
        case Spell::WraithForm: return "Wraith Form";
        case Spell::Wrack: return "Wrack";
        case Spell::EvilPresence: return "Evil Presence";
        case Spell::Wraiths: return "Wraiths";
        case Spell::CloudOfShadow: return "Cloud of Shadow";
        case Spell::WarpNode: return "Warp Node";
        case Spell::BlackWind: return "Black Wind";
        case Spell::ZombieMastery: return "Zombie Mastery";
        case Spell::Famine: return "Famine";
        case Spell::CursedLands: return "Cursed Lands";
        case Spell::CruelUnminding: return "Cruel Unminding";
        case Spell::WordOfDeath: return "Word of Death";
        case Spell::DeathKnights: return "Death Knights";
        case Spell::DeathSpell: return "Death Spell";
        case Spell::AnimateDead: return "Animate Dead";
        case Spell::Pestilence: return "Pestilence";
        case Spell::EternalNight: return "Eternal Night";
        case Spell::EvilOmens: return "Evil Omens";
        case Spell::DeathWish: return "Death Wish";
        case Spell::DemonLord: return "Demon Lord";
        case Spell::MagicSpirit: return "Magic Spirit";
        case Spell::DispelMagic: return "Dispel Magic";
        case Spell::SummoningCircle: return "Summoning Circle";
        case Spell::DisenchantArea: return "Disenchant Area";
        case Spell::RecallHero: return "Recall Hero";
        case Spell::DetectMagic: return "Detect Magic";
        case Spell::EnchantItem: return "Enchant Item";
        case Spell::SummonHero: return "Summon Hero";
        case Spell::Awareness: return "Awareness";
        case Spell::Disjunction: return "Disjunction";
        case Spell::CreateArtifact: return "Create Artifact";
        case Spell::SummonChampion: return "Summon Champion";
        case Spell::SpellOfMastery: return "Spell of Mastery";
        case Spell::SpellOfReturn: return "Spell of Return";
        }
    }
    
    std::ostream& operator<<(std::ostream& os, Spell s) {
        return os << toString(s);
    }
    
}