//
//  Spell.h
//  momom
//
//  Created by Sven de Ridder on 9/24/13.
//  Copyright (c) 2013 svenr. All rights reserved.
//

#ifndef momom_Spell_h
#define momom_Spell_h

#include <ostream>

namespace momom {
    
    constexpr int TotalSpells = 214;
    
    enum class Spell {
        
        None = -1,
        
        // Nature
        EarthToMud = 0,
        ResistElements = 1,
        WallOfStone = 2,
        GiantStrength = 3,
        Web = 4,
        WarBears = 5,
        StoneSkin = 6,
        WaterWalking = 7,
        Sprites = 8,
        EarthLore = 9,
        CracksCall = 10,
        NaturesEye = 11,
        IceBolt = 12,
        GiantSpiders = 13,
        ChangeTerrain = 14,
        PathFinding = 15,
        Cockatrices = 16,
        Transmute = 17,
        NaturesCures = 18,
        Basilisk = 19,
        ElementalArmor = 20,
        Petrify = 21,
        StoneGiant = 22,
        IronSkin = 23,
        IceStorm = 24,
        EarthQuake = 25,
        Gorgons = 26,
        MoveFortress = 27,
        GaiasBlessing = 28,
        EarthElemental = 29,
        Regeneration = 30,
        Behemoth = 31,
        Entangle = 32,
        NaturesAwareness = 33,
        CallLightning = 34,
        Colossus = 35,
        EarthGate = 36,
        HerbMastery = 37,
        GreatWyrm = 38,
        NaturesWrath = 39,
        
        // Sorcery
        ResistMagic = 40,
        DispelMagicTrue = 41,
        FloatingIsland = 42,
        GuardianWind = 43,
        PhantomWarriors = 44,
        Confusion = 45,
        WordOfRecall = 46,
        CounterMagic = 47,
        Nagas = 48,
        PsionicBlast = 49,
        Blur = 50,
        DisenchantTrue = 51,
        Vertigo = 52,
        SpellLock = 53,
        EnchantRoad = 54,
        Flight = 55,
        WindMastery = 56,
        SpellBlast = 57,
        AuraOfMajesty = 58,
        PhantomBeast = 59,
        DisjunctionTrue = 60,
        Invisibility = 61,
        WindWalking = 62,
        Banish = 63,
        StormGiant = 64,
        AirElemental = 65,
        MindStorm = 66,
        Statis = 67,
        MagicImmunity = 68,
        Haste = 69,
        Djinn = 70,
        SpellWard = 71,
        CreatureBinding = 72,
        MassInvisibility = 73,
        GreatUnsummoning = 74,
        SpellBinding = 75,
        FlyingFortress = 76,
        SkyDrake = 77,
        SuppressMagic = 78,
        TimeStop = 79,
        
        // Chaos
        WarpWood = 80,
        Disrupt = 81,
        FireBolt = 82,
        HellHounds = 83,
        Corruption = 84,
        EldritchWeapon = 85,
        WallOfFire = 86,
        Shatter = 87,
        WarpCreature = 88,
        FireElemental = 89,
        LightningBolt = 90,
        FireGiant = 91,
        ChaosChannels = 92,
        FlameBlade = 93,
        Gargoyles = 94,
        Fireball = 95,
        Doombat = 96,
        RaiseVolcano = 97,
        Immolation = 98,
        Chimeras = 99,
        WarpLightning = 100,
        MetalFires = 101,
        ChaosSpawn = 102,
        DoomBolt = 103,
        MagicVortex = 104,
        Efreet = 105,
        FireStorm = 106,
        WarpReality = 107,
        FlameStrike = 108,
        ChaosRift = 109,
        Hydra = 110,
        Disintegrate = 111,
        MeteorStorm = 112,
        GreatWasting = 113,
        CallChaos = 114,
        ChaosSurge = 115,
        DoomMastery = 116,
        GreatDrake = 117,
        CallTheVoid = 118,
        Armageddon = 119,
        
        // Life
        Bless = 120,
        StarFires = 121,
        Endurance = 122,
        HolyWeapon = 123,
        Healing = 124,
        HolyArmor = 125,
        JustCause = 126,
        TrueLight = 127,
        GuardianSpirit = 128,
        Heroism = 129,
        TrueSight = 130,
        PlaneShift = 131,
        Resurrection = 132,
        DispelEvil = 133,
        PlanarSeal = 134,
        Unicorns = 135,
        RaiseDead = 136,
        PlanarTravel = 137,
        HeavenlyLight = 138,
        Prayer = 139,
        Lionheart = 140,
        Incarnation = 141,
        Invulnerability = 142,
        Righteousness = 143,
        Prosperity = 144,
        AltarOfBattle = 145,
        Angel = 146,
        StreamOfLife = 147,
        MassHealing = 148,
        HolyWord = 149,
        HighPrayer = 150,
        Inspirations = 151,
        AstralGate = 152,
        HolyArms = 153,
        Consecration = 154,
        LifeForce = 155,
        Tranquility = 156,
        Crusade = 157,
        ArchAngel = 158,
        CharmOfLife = 159,
        
        // Death
        Skeletons = 160,
        Weakness = 161,
        DarkRituals = 162,
        CloakOfFear = 163,
        BlackSleep = 164,
        Ghouls = 165,
        LifeDrain = 166,
        Terror = 167,
        Darkness = 168,
        ManaLeak = 169,
        DrainPower = 170,
        Possession = 171,
        Lycanthropy = 172,
        BlackPrayer = 173,
        BlackChannels = 174,
        NightStalker = 175,
        Subversion = 176,
        WallOfDarkness = 177,
        Berserk = 178,
        ShadowDemons = 179,
        WraithForm = 180,
        Wrack = 181,
        EvilPresence = 182,
        Wraiths = 183,
        CloudOfShadow = 184,
        WarpNode = 185,
        BlackWind = 186,
        ZombieMastery = 187,
        Famine = 188,
        CursedLands = 189,
        CruelUnminding = 190,
        WordOfDeath = 191,
        DeathKnights = 192,
        DeathSpell = 193,
        AnimateDead = 194,
        Pestilence = 195,
        EternalNight = 196,
        EvilOmens = 197,
        DeathWish = 198,
        DemonLord = 199,
        
        // Arcane
        MagicSpirit = 200,
        DispelMagic = 201,
        SummoningCircle = 202,
        DisenchantArea = 203,
        RecallHero = 204,
        DetectMagic = 205,
        EnchantItem = 206,
        SummonHero = 207,
        Awareness = 208,
        Disjunction = 209,
        CreateArtifact = 210,
        SummonChampion = 211,
        SpellOfMastery = 212,
        SpellOfReturn = 213
    };
    
    const char* toString(Spell);
    
    std::ostream& operator<<(std::ostream&, Spell);
    
    constexpr Spell AllSpells[] = {
        Spell::EarthToMud,
        Spell::ResistElements,
        Spell::WallOfStone,
        Spell::GiantStrength,
        Spell::Web,
        Spell::WarBears,
        Spell::StoneSkin,
        Spell::WaterWalking,
        Spell::Sprites,
        Spell::EarthLore,
        Spell::CracksCall,
        Spell::NaturesEye,
        Spell::IceBolt,
        Spell::GiantSpiders,
        Spell::ChangeTerrain,
        Spell::PathFinding,
        Spell::Cockatrices,
        Spell::Transmute,
        Spell::NaturesCures,
        Spell::Basilisk,
        Spell::ElementalArmor,
        Spell::Petrify,
        Spell::StoneGiant,
        Spell::IronSkin,
        Spell::IceStorm,
        Spell::EarthQuake,
        Spell::Gorgons,
        Spell::MoveFortress,
        Spell::GaiasBlessing,
        Spell::EarthElemental,
        Spell::Regeneration,
        Spell::Behemoth,
        Spell::Entangle,
        Spell::NaturesAwareness,
        Spell::CallLightning,
        Spell::Colossus,
        Spell::EarthGate,
        Spell::HerbMastery,
        Spell::GreatWyrm,
        Spell::NaturesWrath,
        Spell::ResistMagic,
        Spell::DispelMagicTrue,
        Spell::FloatingIsland,
        Spell::GuardianWind,
        Spell::PhantomWarriors,
        Spell::Confusion,
        Spell::WordOfRecall,
        Spell::CounterMagic,
        Spell::Nagas,
        Spell::PsionicBlast,
        Spell::Blur,
        Spell::DisenchantTrue,
        Spell::Vertigo,
        Spell::SpellLock,
        Spell::EnchantRoad,
        Spell::Flight,
        Spell::WindMastery,
        Spell::SpellBlast,
        Spell::AuraOfMajesty,
        Spell::PhantomBeast,
        Spell::DisjunctionTrue,
        Spell::Invisibility,
        Spell::WindWalking,
        Spell::Banish,
        Spell::StormGiant,
        Spell::AirElemental,
        Spell::MindStorm,
        Spell::Statis,
        Spell::MagicImmunity,
        Spell::Haste,
        Spell::Djinn,
        Spell::SpellWard,
        Spell::CreatureBinding,
        Spell::MassInvisibility,
        Spell::GreatUnsummoning,
        Spell::SpellBinding,
        Spell::FlyingFortress,
        Spell::SkyDrake,
        Spell::SuppressMagic,
        Spell::TimeStop,
        Spell::WarpWood,
        Spell::Disrupt,
        Spell::FireBolt,
        Spell::HellHounds,
        Spell::Corruption,
        Spell::EldritchWeapon,
        Spell::WallOfFire,
        Spell::Shatter,
        Spell::WarpCreature,
        Spell::FireElemental,
        Spell::LightningBolt,
        Spell::FireGiant,
        Spell::ChaosChannels,
        Spell::FlameBlade,
        Spell::Gargoyles,
        Spell::Fireball,
        Spell::Doombat,
        Spell::RaiseVolcano,
        Spell::Immolation,
        Spell::Chimeras,
        Spell::WarpLightning,
        Spell::MetalFires,
        Spell::ChaosSpawn,
        Spell::DoomBolt,
        Spell::MagicVortex,
        Spell::Efreet,
        Spell::FireStorm,
        Spell::WarpReality,
        Spell::FlameStrike,
        Spell::ChaosRift,
        Spell::Hydra,
        Spell::Disintegrate,
        Spell::MeteorStorm,
        Spell::GreatWasting,
        Spell::CallChaos,
        Spell::ChaosSurge,
        Spell::DoomMastery,
        Spell::GreatDrake,
        Spell::CallTheVoid,
        Spell::Armageddon,
        Spell::Bless,
        Spell::StarFires,
        Spell::Endurance,
        Spell::HolyWeapon,
        Spell::Healing,
        Spell::HolyArmor,
        Spell::JustCause,
        Spell::TrueLight,
        Spell::GuardianSpirit,
        Spell::Heroism,
        Spell::TrueSight,
        Spell::PlaneShift,
        Spell::Resurrection,
        Spell::DispelEvil,
        Spell::PlanarSeal,
        Spell::Unicorns,
        Spell::RaiseDead,
        Spell::PlanarTravel,
        Spell::HeavenlyLight,
        Spell::Prayer,
        Spell::Lionheart,
        Spell::Incarnation,
        Spell::Invulnerability,
        Spell::Righteousness,
        Spell::Prosperity,
        Spell::AltarOfBattle,
        Spell::Angel,
        Spell::StreamOfLife,
        Spell::MassHealing,
        Spell::HolyWord,
        Spell::HighPrayer,
        Spell::Inspirations,
        Spell::AstralGate,
        Spell::HolyArms,
        Spell::Consecration,
        Spell::LifeForce,
        Spell::Tranquility,
        Spell::Crusade,
        Spell::ArchAngel,
        Spell::CharmOfLife,
        Spell::Skeletons,
        Spell::Weakness,
        Spell::DarkRituals,
        Spell::CloakOfFear,
        Spell::BlackSleep,
        Spell::Ghouls,
        Spell::LifeDrain,
        Spell::Terror,
        Spell::Darkness,
        Spell::ManaLeak,
        Spell::DrainPower,
        Spell::Possession,
        Spell::Lycanthropy,
        Spell::BlackPrayer,
        Spell::BlackChannels,
        Spell::NightStalker,
        Spell::Subversion,
        Spell::WallOfDarkness,
        Spell::Berserk,
        Spell::ShadowDemons,
        Spell::WraithForm,
        Spell::Wrack,
        Spell::EvilPresence,
        Spell::Wraiths,
        Spell::CloudOfShadow,
        Spell::WarpNode,
        Spell::BlackWind,
        Spell::ZombieMastery,
        Spell::Famine,
        Spell::CursedLands,
        Spell::CruelUnminding,
        Spell::WordOfDeath,
        Spell::DeathKnights,
        Spell::DeathSpell,
        Spell::AnimateDead,
        Spell::Pestilence,
        Spell::EternalNight,
        Spell::EvilOmens,
        Spell::DeathWish,
        Spell::DemonLord,
        Spell::MagicSpirit,
        Spell::DispelMagic,
        Spell::SummoningCircle,
        Spell::DisenchantArea,
        Spell::RecallHero,
        Spell::DetectMagic,
        Spell::EnchantItem,
        Spell::SummonHero,
        Spell::Awareness,
        Spell::Disjunction,
        Spell::CreateArtifact,
        Spell::SummonChampion,
        Spell::SpellOfMastery,
        Spell::SpellOfReturn,
    };
    
}

#endif
